In [1]:
import pickle
import numpy as np
import gymnasium as gym

In [39]:
import cv2
import pickle
import os

SAVE_PATH = "G:/Coding/breakout/testing_prioritized/"
FOLDER_NAME = "per_62_10_000_control_he_init_leaky_relu_0_1_image"
REPLAY_NAME = "ep_replay_8629_score_303.0"
# Create a directory to save the frames
if not os.path.exists('frames'):
    os.makedirs('frames')

# Load saved replay
with open(f'{SAVE_PATH}{FOLDER_NAME}/replays/{REPLAY_NAME}.pkl', 'rb') as f:
    ep_replay = pickle.load(f)

# Save frames as images
for i, (state, _, _, _, _) in enumerate(ep_replay):
    # Use the first frame from the stack of 4 frames
    frame = state[:, :, 0]
    frame[frame == 1] = 255
    # if i == 0:
        # print(frame)
    frame_path = os.path.join('frames', f'frame_{i:04d}.png')
    cv2.imwrite(frame_path, frame)

print("Frames saved successfully.")


[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
Frames saved successfully.


In [40]:
import cv2
import os
import shutil

# Parameters
frame_folder = 'frames'
video_name = f'{SAVE_PATH}{FOLDER_NAME}/{REPLAY_NAME}.mp4'
frame_per_second = 20

# Get frame file names
frames = [f for f in os.listdir(frame_folder) if f.endswith('.png')]
frames.sort(key=lambda x: int(x.split('_')[1].split('.')[0]))  # Sort by frame number

# Read the first frame to get height and width
first_frame = cv2.imread(os.path.join(frame_folder, frames[0]))
height, width, _ = first_frame.shape

# Initialize VideoWriter
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(video_name, fourcc, frame_per_second, (width, height))

# Create video from frames
for frame in frames:
    img = cv2.imread(os.path.join(frame_folder, frame))
    out.write(img)

# Finalize the video
out.release()

# Delete the frames folder
shutil.rmtree(frame_folder)

print("Video created successfully.")


Video created successfully.
